import StartModal from "./StartModal";
import DestinationModal from "./DestinationModal";
import StopoversModal from './StopoversModal';
import BackSeatsModal from "./BackSeatsModal";
import InstantApprovalModal from './InstantApprovalModal';
import PriceSuggestionModal from "./PriceSuggestionModal";
import RoundTripModal from "./RoundTripModal";
import NoteModal from './NoteModal';
import ConfimationModal from './ConfimationModal';
import PriceAdjustmentModal from "./PriceAdjustmentModal";
export {StartModal, DestinationModal, StopoversModal, BackSeatsModal, InstantApprovalModal, PriceSuggestionModal, RoundTripModal, NoteModal, ConfimationModal, PriceAdjustmentModal};